export const routePaths = {
  login: '/login',
  overview: '/',
  catalog: '/catalog',
  catalogNew: '/catalog/new',
  catalogEdit: '/catalog/:id/edit',
  orders: '/orders',
  orderDetail: '/orders/:id',
  users: '/users',
  support: '/support',
  supportTicket: '/support/:id',
  content: '/content',
  quotations: '/quotations',
  quotationDetail: '/quotations/:id',
  reports: '/reports',
  forbidden: '/forbidden',
  notFound: '*',
} as const;